// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func BuzzedIn() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div style=\"display:flex; flex-direction:column; align-items:center;\"><h1>Buzzed In</h1><div style=\"display:flex; flex-direction:column;\" id=\"buzzed-in\"></div></div><script>\r\n        function updateBuzzedIn() {\r\n            fetch('/buzzed-in', {method:\"POST\"})\r\n                .then(response => response.json())\r\n                .then(data => {\r\n                    const leaderboardBody = document.getElementById('buzzed-in');\r\n                    leaderboardBody.innerHTML = `\r\n                        ${data.map((player) => \r\n                                `<div style=\"display:flex; flex:1; cursor:pointer; background-color:#ccc; padding:0.25rem; margin:0.25rem; border-radius:0.25rem;\">\r\n                                    <td style=\"display:inline-block; text-align:center; padding:0.5rem;\">${player[0]} | ${player[1]}</td>\r\n                                </div>`\r\n                        ).join('')}\r\n                    `;\r\n                });\r\n        }\r\n        updateBuzzedIn();\r\n        setInterval(updateBuzzedIn, 100);\r\n    </script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
